# Dependencies
markdown:            kramdown
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            DevJoe
tagline:          'All out of bubblegum'
description:      'Welcome to my personal development profile.  This site has some of my personal projects on it.'
url:              jfehrman.github.io

author:
  name:           'Joseph Fehrman'
  url:            jfehrman.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:         https://github.com/jfehrman/jfehrman.github.io.git 

plugins:        ['jekyll-paginate']
